email = "popu-servers+jenkins@populate.tools "
pipeline {
    agent any
    environment {
        PATH = "$HOME/.rbenv/shims:$PATH"
        GOBIERTO_ETL_UTILS = "/var/www/gobierto-etl-utils/current/"
        MATARO_ETL = "/var/www/gobierto-etl-mataro/current/"
        WORKING_DIR = "/tmp/mataro_costs"
        DATASET_NAME = "Costes"
        DATASET_SLUG = "costes"
        DATASET_TABLE_NAME = "costes"
        // Variables that must be defined via Jenkins UI:
        // GOBIERTO_DATA_DEST_URL = ""
    }
    options {
        retry(3)
    }
    stages {
        stage('Clean working dir') {
          steps {
              sh "rm -rf ${WORKING_DIR}"
              sh "mkdir -p ${WORKING_DIR}"
          }
        }
        stage('Extract > Download 2019 data sources') {
            steps {
                sh "cd ${GOBIERTO_ETL_UTILS}; ruby operations/download/run.rb 'https://dadesobertes.mataro.cat/costos_2019.csv' ${WORKING_DIR}/costos_2019.csv"
            }
        }
        stage('Extract > Convert 2019 data to UTF8') {
            steps {
                sh "cd ${GOBIERTO_ETL_UTILS}; ruby operations/convert-to-utf8/run.rb ${WORKING_DIR}/costos_2019.csv ${WORKING_DIR}/costos_2019_utf8.csv ISO-8859-1"
            }
        }
        stage('Extract > Check 2019 CSV format') {
            steps {
                sh "cd ${GOBIERTO_ETL_UTILS}; ruby operations/check-csv/run.rb ${WORKING_DIR}/costos_2019_utf8.csv"
            }
        }
        stage('Load > Upload 2019 data to Gobierto data') {
            steps {
              sh '''#!/bin/bash
                source ${MATARO_ETL}/.rbenv-vars;
                cd ${GOBIERTO_ETL_UTILS};
                ruby operations/gobierto_data/upload-dataset/run.rb \
                  --api-token $API_TOKEN \
                  --name "$DATASET_NAME" \
                  --slug $DATASET_SLUG \
                  --table-name $DATASET_TABLE_NAME \
                  --gobierto-url $GOBIERTO_DATA_DEST_URL \
                  --file-path ${WORKING_DIR}/costos_2019_utf8.csv
              '''
            }
        }
        stage('Extract > Download 2020 data sources') {
            steps {
                sh "cd ${GOBIERTO_ETL_UTILS}; ruby operations/download/run.rb 'https://dadesobertes.mataro.cat/costos_2020.csv' ${WORKING_DIR}/costos_2020.csv"
            }
        }
        stage('Extract > Convert 2020 data to UTF8') {
            steps {
                sh "cd ${GOBIERTO_ETL_UTILS}; ruby operations/convert-to-utf8/run.rb ${WORKING_DIR}/costos_2020.csv ${WORKING_DIR}/costos_2020_utf8.csv ISO-8859-1"
            }
        }
        stage('Extract > Check 2020 CSV format') {
            steps {
                sh "cd ${GOBIERTO_ETL_UTILS}; ruby operations/check-csv/run.rb ${WORKING_DIR}/costos_2020_utf8.csv"
            }
        }
        stage('Load > Upload 2020 data to Gobierto data') {
            steps {
              sh '''#!/bin/bash
                source ${MATARO_ETL}/.rbenv-vars;
                cd ${GOBIERTO_ETL_UTILS};
                ruby operations/gobierto_data/upload-dataset/run.rb \
                  --api-token $API_TOKEN \
                  --name "$DATASET_NAME" \
                  --slug $DATASET_SLUG \
                  --table-name $DATASET_TABLE_NAME \
                  --gobierto-url $GOBIERTO_DATA_DEST_URL \
                  --file-path ${WORKING_DIR}/costos_2020_utf8.csv \
                  --append
              '''
            }
        }
        stage('Extract > Download 2021 data sources') {
            steps {
                sh "cd ${GOBIERTO_ETL_UTILS}; ruby operations/download/run.rb 'https://dadesobertes.mataro.cat/costos_2021.csv' ${WORKING_DIR}/costos_2021.csv"
            }
        }
        stage('Extract > Convert 2021 data to UTF8') {
            steps {
                sh "cd ${GOBIERTO_ETL_UTILS}; ruby operations/convert-to-utf8/run.rb ${WORKING_DIR}/costos_2021.csv ${WORKING_DIR}/costos_2021_utf8.csv ISO-8859-1"
            }
        }
        stage('Extract > Check 2021 CSV format') {
            steps {
                sh "cd ${GOBIERTO_ETL_UTILS}; ruby operations/check-csv/run.rb ${WORKING_DIR}/costos_2021_utf8.csv"
            }
        }
        stage('Load > Upload 2021 data to Gobierto data') {
            steps {
              sh '''#!/bin/bash
                source ${MATARO_ETL}/.rbenv-vars;
                cd ${GOBIERTO_ETL_UTILS};
                ruby operations/gobierto_data/upload-dataset/run.rb \
                  --api-token $API_TOKEN \
                  --name "$DATASET_NAME" \
                  --slug $DATASET_SLUG \
                  --table-name $DATASET_TABLE_NAME \
                  --gobierto-url $GOBIERTO_DATA_DEST_URL \
                  --file-path ${WORKING_DIR}/costos_2021_utf8.csv \
                  --append
              '''
            }
        }
        stage('Extract > Download 2022 data sources') {
            steps {
                sh "cd ${GOBIERTO_ETL_UTILS}; ruby operations/download/run.rb 'https://dadesobertes.mataro.cat/costos_2022.csv' ${WORKING_DIR}/costos_2022.csv"
            }
        }
        stage('Extract > Convert 2022 data to UTF8') {
            steps {
                sh "cd ${GOBIERTO_ETL_UTILS}; ruby operations/convert-to-utf8/run.rb ${WORKING_DIR}/costos_2022.csv ${WORKING_DIR}/costos_2022_utf8.csv ISO-8859-1"
            }
        }
        stage('Extract > Check 2022 CSV format') {
            steps {
                sh "cd ${GOBIERTO_ETL_UTILS}; ruby operations/check-csv/run.rb ${WORKING_DIR}/costos_2022_utf8.csv"
            }
        }
        stage('Load > Upload 2022 data to Gobierto data') {
            steps {
              sh '''#!/bin/bash
                source ${MATARO_ETL}/.rbenv-vars;
                cd ${GOBIERTO_ETL_UTILS};
                ruby operations/gobierto_data/upload-dataset/run.rb \
                  --api-token $API_TOKEN \
                  --name "$DATASET_NAME" \
                  --slug $DATASET_SLUG \
                  --table-name $DATASET_TABLE_NAME \
                  --gobierto-url $GOBIERTO_DATA_DEST_URL \
                  --file-path ${WORKING_DIR}/costos_2022_utf8.csv \
                  --append
              '''
            }
        }
        stage('Extract > Download 2023 data sources') {
            steps {
                sh "cd ${GOBIERTO_ETL_UTILS}; ruby operations/download/run.rb 'https://dadesobertes.mataro.cat/costos_2023.csv' ${WORKING_DIR}/costos_2023.csv"
            }
        }
        stage('Extract > Convert 2023 data to UTF8') {
            steps {
                sh "cd ${GOBIERTO_ETL_UTILS}; ruby operations/convert-to-utf8/run.rb ${WORKING_DIR}/costos_2023.csv ${WORKING_DIR}/costos_2023_utf8.csv ISO-8859-1"
            }
        }
        stage('Extract > Check 2023 CSV format') {
            steps {
                sh "cd ${GOBIERTO_ETL_UTILS}; ruby operations/check-csv/run.rb ${WORKING_DIR}/costos_2023_utf8.csv"
            }
        }
        stage('Load > Upload 2023 data to Gobierto data') {
            steps {
              sh '''#!/bin/bash
                source ${MATARO_ETL}/.rbenv-vars;
                cd ${GOBIERTO_ETL_UTILS};
                ruby operations/gobierto_data/upload-dataset/run.rb \
                  --api-token $API_TOKEN \
                  --name "$DATASET_NAME" \
                  --slug $DATASET_SLUG \
                  --table-name $DATASET_TABLE_NAME \
                  --gobierto-url $GOBIERTO_DATA_DEST_URL \
                  --file-path ${WORKING_DIR}/costos_2023_utf8.csv \
                  --append
              '''
            }
        }
    }
    post {
        failure {
            echo 'This will run only if failed'
            mail body: "Project: ${env.JOB_NAME} - Build Number: ${env.BUILD_NUMBER} - URL de build: ${env.BUILD_URL}",
                charset: 'UTF-8',
                subject: "ERROR CI: Project name -> ${env.JOB_NAME}",
                to: email
        }
    }
}
