email = "popu-servers+jenkins@populate.tools "
pipeline {
    agent any
    environment {
        PATH = "$HOME/.rbenv/shims:$PATH"
        GOBIERTO_ETL_UTILS = "/var/www/gobierto-etl-utils/current/"
        MATARO_ETL = "/var/www/gobierto-etl-mataro/current/"
        WORKING_DIR = "/tmp/mataro_debt"
        // Variables that must be defined via Jenkins UI:
        // GOBIERTO_DATA_DEST_URL = ""
    }
    options {
        retry(3)
    }
    stages {
        stage('Clean working dir') {
          steps {
              sh "rm -rf ${WORKING_DIR}"
              sh "mkdir -p ${WORKING_DIR}"
          }
        }
        stage('Extract > 01 file') {
            steps {
                sh "cd ${GOBIERTO_ETL_UTILS}; ruby operations/download/run.rb 'https://docs.google.com/spreadsheets/d/e/2PACX-1vTWlCJ-zBt-7ktYh1R_F3_bo2AHR1m1NpeB-5xl0YQSQ7fq48C6-nRa24RuI_ySYq_C6AHUwLqeyCJa/pub?gid=500773047&single=true&output=csv' ${WORKING_DIR}/01.csv"
            }
        }
        stage('Extract > 02 file') {
            steps {
                sh "cd ${GOBIERTO_ETL_UTILS}; ruby operations/download/run.rb 'https://docs.google.com/spreadsheets/d/e/2PACX-1vQpoa5CuOHTS9gNul_OoZPmBrtsguianUGJX0cne5k4M81IbGDWlVlwkqmG0r2gOanpueLTXe5KLO82/pub?gid=169495231&single=true&output=csv' ${WORKING_DIR}/02.csv"
            }
        }
        stage('Extract > 03 file') {
            steps {
                sh "cd ${GOBIERTO_ETL_UTILS}; ruby operations/download/run.rb 'https://docs.google.com/spreadsheets/d/e/2PACX-1vTGPYVs9gxA6zrqT3vY5w6gVRH7aH-f-CwC9pde3jIHUUWMeaY_92QKe62zPJPVbiyY8yuTEBUy_aa7/pub?gid=427327543&single=true&output=csv' ${WORKING_DIR}/03.csv"
            }
        }
        stage('Extract > Check 01 CSV format') {
            steps {
                sh "cd ${GOBIERTO_ETL_UTILS}; ruby operations/check-csv/run.rb ${WORKING_DIR}/01.csv"
            }
        }
        stage('Extract > Check 02 CSV format') {
            steps {
                sh "cd ${GOBIERTO_ETL_UTILS}; ruby operations/check-csv/run.rb ${WORKING_DIR}/02.csv"
            }
        }
        stage('Extract > Check 03 CSV format') {
            steps {
                sh "cd ${GOBIERTO_ETL_UTILS}; ruby operations/check-csv/run.rb ${WORKING_DIR}/03.csv"
            }
        }
        stage('Load > Upload 01 data to Gobierto data') {
            steps {
              sh '''#!/bin/bash
                source ${MATARO_ETL}/.rbenv-vars;
                cd ${GOBIERTO_ETL_UTILS};
                ruby operations/gobierto_data/upload-dataset/run.rb \
                  --api-token $API_TOKEN \
                  --name "Deute total" \
                  --slug "deute-total" \
                  --table-name "deute_total" \
                  --gobierto-url $GOBIERTO_DATA_DEST_URL \
                  --file-path ${WORKING_DIR}/01.csv
              '''
            }
        }
        stage('Load > Upload 02 data to Gobierto data') {
            steps {
              sh '''#!/bin/bash
                source ${MATARO_ETL}/.rbenv-vars;
                cd ${GOBIERTO_ETL_UTILS};
                ruby operations/gobierto_data/upload-dataset/run.rb \
                  --api-token $API_TOKEN \
                  --name "Deute entitat" \
                  --slug "deute-entitat" \
                  --table-name "deute_entitat" \
                  --gobierto-url $GOBIERTO_DATA_DEST_URL \
                  --file-path ${WORKING_DIR}/02.csv
              '''
            }
        }
        stage('Load > Upload 03 data to Gobierto data') {
            steps {
              sh '''#!/bin/bash
                source ${MATARO_ETL}/.rbenv-vars;
                cd ${GOBIERTO_ETL_UTILS};
                ruby operations/gobierto_data/upload-dataset/run.rb \
                  --api-token $API_TOKEN \
                  --name "Evolucio" \
                  --slug "evolucio" \
                  --table-name "evolucio" \
                  --gobierto-url $GOBIERTO_DATA_DEST_URL \
                  --file-path ${WORKING_DIR}/03.csv
              '''
            }
        }
    }
    post {
        failure {
            echo 'This will run only if failed'
            mail body: "Project: ${env.JOB_NAME} - Build Number: ${env.BUILD_NUMBER} - URL de build: ${env.BUILD_URL}",
                charset: 'UTF-8',
                subject: "ERROR CI: Project name -> ${env.JOB_NAME}",
                to: email
        }
    }
}
