email = "popu-servers+jenkins@populate.tools "
pipeline {
    agent any
    environment {
        PATH = "/home/ubuntu/.rbenv/shims:$PATH"
        GOBIERTO_ETL_UTILS = "/var/www/gobierto-etl-utils/current/"
        MATARO_ETL = "/var/www/gobierto-etl-mataro/current/"
        WORKING_DIR = "/tmp/mataro"
        // Variables that must be defined via Jenkins UI:
        // GOBIERTO = "/var/www/gobierto/current"
        // DOMAIN = "pressupost.mataro.cat"
    }
    stages {
        stage('Clean working dir') {
          steps {
              sh "rm -rf ${WORKING_DIR}"
              sh "mkdir -p ${WORKING_DIR}"
          }
        }
        stage('Create organization file') {
            steps {
              sh "echo '8121' > ${WORKING_DIR}/organization.id.txt"
            }
        }
        stage('Clear previous data') {
            steps {
              sh "cd ${GOBIERTO_ETL_UTILS}; ruby operations/gobierto_budgets/clear-budgets/run.rb ${WORKING_DIR}/organization.id.txt 2019"
              sh "cd ${GOBIERTO_ETL_UTILS}; ruby operations/gobierto_budgets/clear-budgets/run.rb ${WORKING_DIR}/organization.id.txt 2020"
              sh "cd ${GOBIERTO_ETL_UTILS}; ruby operations/gobierto_budgets/clear-budgets/run.rb ${WORKING_DIR}/organization.id.txt 2021"
            }
        }
        stage('Extract > Download data sources') {
            steps {
                sh "cd ${GOBIERTO_ETL_UTILS}; ruby operations/download/run.rb 'http://dadesobertes.mataro.cat/pressupost_2019.csv' ${WORKING_DIR}/pressupost_2019.csv"
                sh "cd ${GOBIERTO_ETL_UTILS}; ruby operations/download/run.rb 'http://dadesobertes.mataro.cat/pressupost_2020.csv' ${WORKING_DIR}/pressupost_2020.csv"
            }
        }
        stage('Extract > Convert data to UTF8') {
            steps {
                sh "cd ${GOBIERTO_ETL_UTILS}; ruby operations/convert-to-utf8/run.rb ${WORKING_DIR}/pressupost_2019.csv ${WORKING_DIR}/pressupost_2019_utf8.csv ISO-8859-1"
                sh "cd ${GOBIERTO_ETL_UTILS}; ruby operations/convert-to-utf8/run.rb ${WORKING_DIR}/pressupost_2020.csv ${WORKING_DIR}/pressupost_2020_utf8.csv ISO-8859-1"
            }
        }
        stage('Extract > Clean wrong quotes') {
            steps {
                sh "cd ${MATARO_ETL}; ruby operations/gobierto_budgets/clean-quotes/run.rb ${WORKING_DIR}/pressupost_2019_utf8.csv ${WORKING_DIR}/pressupost_2019_utf8_clean.csv"
                sh "cd ${MATARO_ETL}; ruby operations/gobierto_budgets/clean-quotes/run.rb ${WORKING_DIR}/pressupost_2020_utf8.csv ${WORKING_DIR}/pressupost_2020_utf8_clean.csv"
            }
        }
        stage('Extract > Check CSV format') {
            steps {
                sh "cd ${GOBIERTO_ETL_UTILS}; ruby operations/check-csv/run.rb ${WORKING_DIR}/pressupost_2019_utf8_clean.csv"
                sh "cd ${GOBIERTO_ETL_UTILS}; ruby operations/check-csv/run.rb ${WORKING_DIR}/pressupost_2020_utf8_clean.csv"
            }
        }
        stage('Transform > Transform planned budgets data files') {
            steps {
                sh "cd ${MATARO_ETL}; ruby operations/gobierto_budgets/transform-planned/run.rb ${WORKING_DIR}/pressupost_2019_utf8_clean.csv ${WORKING_DIR}/budgets-planned-2019-transformed.json 2019"
                sh "cd ${MATARO_ETL}; ruby operations/gobierto_budgets/transform-planned/run.rb ${WORKING_DIR}/pressupost_2020_utf8_clean.csv ${WORKING_DIR}/budgets-planned-2020-transformed.json 2020"
            }
        }
        stage('Transform > Transform executed budgets data files') {
            steps {
                sh "cd ${MATARO_ETL}; ruby operations/gobierto_budgets/transform-executed/run.rb ${WORKING_DIR}/pressupost_2019_utf8_clean.csv ${WORKING_DIR}/budgets-executed-2019-transformed.json 2019"
                sh "cd ${MATARO_ETL}; ruby operations/gobierto_budgets/transform-executed/run.rb ${WORKING_DIR}/pressupost_2020_utf8_clean.csv ${WORKING_DIR}/budgets-executed-2020-transformed.json 2020"
            }
        }
        stage('Transform > Transform planned updated budgets data files') {
            steps {
                sh "cd ${MATARO_ETL}; ruby operations/gobierto_budgets/transform-planned-updated/run.rb ${WORKING_DIR}/pressupost_2019_utf8_clean.csv ${WORKING_DIR}/budgets-planned-updated-2019-transformed.json 2019"
                sh "cd ${MATARO_ETL}; ruby operations/gobierto_budgets/transform-planned-updated/run.rb ${WORKING_DIR}/pressupost_2020_utf8_clean.csv ${WORKING_DIR}/budgets-planned-updated-2020-transformed.json 2020"
            }
        }
        stage('Load > Import planned budgets') {
            steps {
                sh "cd ${GOBIERTO_ETL_UTILS}; ruby operations/gobierto_budgets/import-planned-budgets/run.rb ${WORKING_DIR}/budgets-planned-2019-transformed.json 2019"
                sh "cd ${GOBIERTO_ETL_UTILS}; ruby operations/gobierto_budgets/import-planned-budgets/run.rb ${WORKING_DIR}/budgets-planned-2020-transformed.json 2020"
            }
        }
        stage('Load > Import executed budgets') {
            steps {
                sh "cd ${GOBIERTO_ETL_UTILS}; ruby operations/gobierto_budgets/import-executed-budgets/run.rb ${WORKING_DIR}/budgets-executed-2019-transformed.json 2019"
                sh "cd ${GOBIERTO_ETL_UTILS}; ruby operations/gobierto_budgets/import-executed-budgets/run.rb ${WORKING_DIR}/budgets-executed-2020-transformed.json 2020"
            }
        }
        stage('Load > Import planned updated budgets') {
            steps {
                sh "cd ${GOBIERTO_ETL_UTILS}; ruby operations/gobierto_budgets/import-planned-budgets-updated/run.rb ${WORKING_DIR}/budgets-planned-updated-2019-transformed.json 2019"
                sh "cd ${GOBIERTO_ETL_UTILS}; ruby operations/gobierto_budgets/import-planned-budgets-updated/run.rb ${WORKING_DIR}/budgets-planned-updated-2020-transformed.json 2020"
            }
        }
        stage('Load > Import custom categories') {
            steps {
                sh "cd ${GOBIERTO}; bin/rails runner ${MATARO_ETL}/operations/gobierto_budgets/extract-custom-categories/run.rb ${WORKING_DIR}/pressupost_2019_utf8_clean.csv ${DOMAIN}"
                sh "cd ${GOBIERTO}; bin/rails runner ${MATARO_ETL}/operations/gobierto_budgets/extract-custom-categories/run.rb ${WORKING_DIR}/pressupost_2020_utf8_clean.csv ${DOMAIN}"
            }
        }
        stage('Load > Calculate totals') {
            steps {
              sh "cd ${GOBIERTO_ETL_UTILS}; ruby operations/gobierto_budgets/update_total_budget/run.rb '2018 2019 2020' ${WORKING_DIR}/organization.id.txt"
            }
        }
        stage('Load > Calculate bubbles') {
            steps {
              sh "cd ${GOBIERTO_ETL_UTILS}; ruby operations/gobierto_budgets/bubbles/run.rb ${WORKING_DIR}/organization.id.txt"
            }
        }
        stage('Load > Calculate annual data') {
            steps {
              sh "cd ${GOBIERTO}; bin/rails runner ${GOBIERTO_ETL_UTILS}/operations/gobierto_budgets/annual_data/run.rb '2018 2019 2020' ${WORKING_DIR}/organization.id.txt"
            }
        }
        stage('Load > Publish activity') {
            steps {
              sh "cd ${GOBIERTO}; bin/rails runner ${GOBIERTO_ETL_UTILS}/operations/gobierto/publish-activity/run.rb budgets_updated ${WORKING_DIR}/organization.id.txt"
            }
        }
        stage('Clear cache') {
          steps {
            sh "cd ${GOBIERTO}; bin/rails runner ${GOBIERTO_ETL_UTILS}/operations/gobierto/clear-cache/run.rb"
          }
        }
    }
    post {
        failure {
            echo 'This will run only if failed'
            mail body: "Project: ${env.JOB_NAME} - Build Number: ${env.BUILD_NUMBER} - URL de build: ${env.BUILD_URL}",
                charset: 'UTF-8',
                subject: "ERROR CI: Project name -> ${env.JOB_NAME}",
                to: email
        }
    }
}
